name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Создаём папку для артефакта вне репозитория и копируем всё, кроме dist
      - name: Prepare artifact
        run: |
          mkdir -p ../artifact
          rsync -av --exclude='dist' ./ ../artifact/

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ../artifact   # указываем путь к папке с артефактом

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
